language: scala
scala:
  - 2.10.4
jdk:
  - openjdk8
  - openjdk7
sudo: false
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test scalastyle
  - sbt -jvm-opts travis/jvmopts.test scripted
