language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8
sudo: false
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test scalastyle
  - sbt -jvm-opts travis/jvmopts.test scripted
